spring:
  application:
    name: taskservice
server:
  port: 8080
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://google/taskservice?cloudSqlInstance=springboot-cloudsql:us-central1:springboot-cloudsql&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=root"
    password: "root"
    username: "root"
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
